/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ExampleCalc__factory } from "./ExampleCalc__factory";
export { ICalc__factory } from "./ICalc__factory";
